<?php

namespace App\Enums;

use App\Enums\Concerns\EnumToArray;

enum Currency: string
{
    use EnumToArray;

    case AFN = 'AFN';
    case ALL = 'ALL';
    case ANG = 'ANG';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AWG = 'AWG';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BDT = 'BDT';
    case BBD = 'BBD';
    case BGN = 'BGN';
    case BMD = 'BMD';
    case BND = 'BND';
    case BOB = 'BOB';
    case BRL = 'BRL';
    case BSD = 'BSD';
    case BWP = 'BWP';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case CAD = 'CAD';
    case CHF = 'CHF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case CUP = 'CUP';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case EGP = 'EGP';
    case EUR = 'EUR';
    case FJD = 'FJD';
    case FKP = 'FKP';
    case GBP = 'GBP';
    case GIP = 'GIP';
    case GTQ = 'GTQ';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case IRR = 'IRR';
    case ISK = 'ISK';
    case JMD = 'JMD';
    case JPY = 'JPY';
    case KGS = 'KGS';
    case KHR = 'KHR';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KYD = 'KYD';
    case KZT = 'KZT';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LRD = 'LRD';
    case LTL = 'LTL';
    case LVL = 'LVL';
    case MKD = 'MKD';
    case MNT = 'MNT';
    case MUR = 'MUR';
    case MXN = 'MXN';
    case MYR = 'MYR';
    case MZN = 'MZN';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case SAR = 'SAR';
    case SBD = 'SBD';
    case SCR = 'SCR';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SHP = 'SHP';
    case SOS = 'SOS';
    case SRD = 'SRD';
    case SVC = 'SVC';
    case SYP = 'SYP';
    case THB = 'THB';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case UAH = 'UAH';
    case USD = 'USD';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VEF = 'VEF';
    case VND = 'VND';
    case XCD = 'XCD';
    case YER = 'YER';
    case ZAR = 'ZAR';

    public function symbol(): string
    {
        return match ($this) {
            self::AFN => '؋',
            self::ALL => 'Lek',
            self::ANG => 'ƒ',
            self::ARS => '$',
            self::AUD => '$',
            self::AWG => 'ƒ',
            self::AZN => 'ман',
            self::BAM => 'KM',
            self::BDT => '৳',
            self::BBD => '$',
            self::BGN => 'лв',
            self::BMD => '$',
            self::BND => '$',
            self::BOB => '$b',
            self::BRL => 'R$',
            self::BSD => '$',
            self::BWP => 'P',
            self::BYR => '₽',
            self::BZD => 'BZ$',
            self::CAD => '$',
            self::CHF => 'CHF',
            self::CLP => '$',
            self::CNY => '¥',
            self::COP => '$',
            self::CRC => '₡',
            self::CUP => '₱',
            self::CZK => 'Kč',
            self::DKK => 'kr',
            self::DOP => 'RD$',
            self::EGP => '£',
            self::EUR => '€',
            self::FJD => '$',
            self::FKP => '£',
            self::GBP => '£',
            self::GIP => '£',
            self::GTQ => 'Q',
            self::GYD => '$',
            self::HKD => '$',
            self::HNL => 'L',
            self::HRK => 'kn',
            self::HUF => 'Ft',
            self::IDR => 'Rp',
            self::ILS => '₪',
            self::IRR => '﷼',
            self::ISK => 'kr',
            self::JMD => 'J$',
            self::JPY => '¥',
            self::KGS => 'лв',
            self::KHR => '៛',
            self::KPW => '₩',
            self::KRW => '₩',
            self::KYD => '$',
            self::KZT => 'лв',
            self::LAK => '₭',
            self::LBP => '£',
            self::LKR => '₨',
            self::LRD => '$',
            self::LTL => 'Lt',
            self::LVL => 'Ls',
            self::MKD => 'ден',
            self::MNT => '₮',
            self::MUR => '₨',
            self::MXN => '$',
            self::MYR => 'RM',
            self::MZN => 'MT',
            self::NGN => '₦',
            self::NIO => 'C$',
            self::NOK => 'kr',
            self::NPR => '₨',
            self::NZD => '$',
            self::OMR => '﷼',
            self::PAB => 'B/.',
            self::PEN => 'S/.',
            self::PHP => 'Php',
            self::PKR => '₨',
            self::PLN => 'zł',
            self::PYG => 'Gs',
            self::QAR => '﷼',
            self::RON => 'lei',
            self::RSD => 'Дин.',
            self::RUB => 'руб',
            self::SAR => '﷼',
            self::SBD => '$',
            self::SCR => '₨',
            self::SEK => 'kr',
            self::SGD => '$',
            self::SHP => '£',
            self::SOS => 'S',
            self::SRD => '$',
            self::SVC => '$',
            self::SYP => '£',
            self::THB => '฿',
            self::TRY => 'TL',
            self::TTD => 'TT$',
            self::TWD => 'NT$',
            self::UAH => '₴',
            self::USD => '$',
            self::UYU => '$U',
            self::UZS => 'лв',
            self::VEF => 'Bs',
            self::VND => '₫',
            self::XCD => '$',
            self::YER => '﷼',
            self::ZAR => 'R',
        };
    }

    public function fullName(): string
    {
        return match ($this) {
            self::AFN => 'Afghani',
            self::ALL => 'Lek',
            self::ANG => 'Netherlands Antillian Guilder',
            self::ARS => 'Argentine Peso',
            self::AUD => 'Australian Dollar',
            self::AWG => 'Aruban Guilder',
            self::AZN => 'Azerbaijanian Manat',
            self::BAM => 'Convertible Marks',
            self::BDT => 'Bangladeshi Taka',
            self::BBD => 'Barbados Dollar',
            self::BGN => 'Bulgarian Lev',
            self::BMD => 'Bermudian Dollar',
            self::BND => 'Brunei Dollar',
            self::BOB => 'BOV Boliviano Mvdol',
            self::BRL => 'Brazilian Real',
            self::BSD => 'Bahamian Dollar',
            self::BWP => 'Pula',
            self::BYR => 'Belarussian Ruble',
            self::BZD => 'Belize Dollar',
            self::CAD => 'Canadian Dollar',
            self::CHF => 'Swiss Franc',
            self::CLP => 'CLF Chilean Peso Unidades de fomento',
            self::CNY => 'Yuan Renminbi',
            self::COP => 'COU Colombian Peso Unidad de Valor Real',
            self::CRC => 'Costa Rican Colon',
            self::CUP => 'CUC Cuban Peso Peso Convertible',
            self::CZK => 'Czech Koruna',
            self::DKK => 'Danish Krone',
            self::DOP => 'Dominican Peso',
            self::EGP => 'Egyptian Pound',
            self::EUR => 'Euro',
            self::FJD => 'Fiji Dollar',
            self::FKP => 'Falkland Islands Pound',
            self::GBP => 'Pound Sterling',
            self::GIP => 'Gibraltar Pound',
            self::GTQ => 'Quetzal',
            self::GYD => 'Guyana Dollar',
            self::HKD => 'Hong Kong Dollar',
            self::HNL => 'Lempira',
            self::HRK => 'Croatian Kuna',
            self::HUF => 'Forint',
            self::IDR => 'Rupiah',
            self::ILS => 'New Israeli Sheqel',
            self::IRR => 'Iranian Rial',
            self::ISK => 'Iceland Krona',
            self::JMD => 'Jamaican Dollar',
            self::JPY => 'Yen',
            self::KGS => 'Som',
            self::KHR => 'Riel',
            self::KPW => 'North Korean Won',
            self::KRW => 'Won',
            self::KYD => 'Cayman Islands Dollar',
            self::KZT => 'Tenge',
            self::LAK => 'Kip',
            self::LBP => 'Lebanese Pound',
            self::LKR => 'Sri Lanka Rupee',
            self::LRD => 'Liberian Dollar',
            self::LTL => 'Lithuanian Litas',
            self::LVL => 'Latvian Lats',
            self::MKD => 'Denar',
            self::MNT => 'Tugrik',
            self::MUR => 'Mauritius Rupee',
            self::MXN => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]',
            self::MYR => 'Malaysian Ringgit',
            self::MZN => 'Metical',
            self::NGN => 'Naira',
            self::NIO => 'Cordoba Oro',
            self::NOK => 'Norwegian Krone',
            self::NPR => 'Nepalese Rupee',
            self::NZD => 'New Zealand Dollar',
            self::OMR => 'Rial Omani',
            self::PAB => 'USD Balboa US Dollar',
            self::PEN => 'Nuevo Sol',
            self::PHP => 'Philippine Peso',
            self::PKR => 'Pakistan Rupee',
            self::PLN => 'Zloty',
            self::PYG => 'Guarani',
            self::QAR => 'Qatari Rial',
            self::RON => 'New Leu',
            self::RSD => 'Serbian Dinar',
            self::RUB => 'Russian Ruble',
            self::SAR => 'Saudi Riyal',
            self::SBD => 'Solomon Islands Dollar',
            self::SCR => 'Seychelles Rupee',
            self::SEK => 'Swedish Krona',
            self::SGD => 'Singapore Dollar',
            self::SHP => 'Saint Helena Pound',
            self::SOS => 'Somali Shilling',
            self::SRD => 'Surinam Dollar',
            self::SVC => 'USD El Salvador Colon US Dollar',
            self::SYP => 'Syrian Pound',
            self::THB => 'Baht',
            self::TRY => 'Turkish Lira',
            self::TTD => 'Trinidad and Tobago Dollar',
            self::TWD => 'New Taiwan Dollar',
            self::UAH => 'Hryvnia',
            self::USD => 'US Dollar',
            self::UYU => 'UYI Uruguay Peso en Unidades Indexadas',
            self::UZS => 'Uzbekistan Sum',
            self::VEF => 'Bolivar Fuerte',
            self::VND => 'Dong',
            self::XCD => 'East Caribbean Dollar',
            self::YER => 'Yemeni Rial',
            self::ZAR => 'Rand',
        };
    }
}
